version: "3.5"

services:
  api:
    build:
      context: "."
    command:
      - npm
      - start
    env_file:
      - ./backend.env
    ports:
      - 4000:4000

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    command: mongod
